name: colorectal_cancer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pillow>=10.0.0
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - pip
  - pip:
    - tensorboard>=2.13.0
    - pytest>=7.4.0
    - black>=23.0.0
    - flake8>=6.0.0
