#!/bin/bash
# scripts/download_data.sh

echo "========================================"
echo "NCT-CRC-HE-100K Dataset Download"
echo "========================================"
echo ""
echo "Dataset Information:"
echo "  Name: NCT-CRC-HE-100K"
echo "  Source: Zenodo (European research repository)"
echo "  License: CC BY 4.0"
echo "  Size: ~11.7 GB"
echo "  Images: 100,000 histopathological patches"
echo "  Classes: 9 tissue types (we use NORM and TUM)"
echo ""
echo "Legal Notice:"
echo "  ✓ This dataset is hosted on Zenodo"
echo "  ✓ Direct HTTP download (no torrents)"
echo "  ✓ Fully legal in Germany and EU"
echo "  ✓ From German institutions (NCT Heidelberg, UMM Mannheim)"
echo ""
echo "========================================"
echo "Download Instructions:"
echo "========================================"
echo ""
echo "Option 1: Manual Download (Recommended)"
echo "  1. Visit: https://zenodo.org/records/1214456"
echo "  2. Download: NCT-CRC-HE-100K.zip (11.7 GB)"
echo "  3. Extract to: data/raw/"
echo "  4. Final structure: data/raw/NCT-CRC-HE-100K/<class>/*.tif"
echo ""
echo "Option 2: Command Line (using wget)"
echo "  wget -O data/raw/NCT-CRC-HE-100K.zip 'https://zenodo.org/records/1214456/files/NCT-CRC-HE-100K.zip?download=1'"
echo "  unzip data/raw/NCT-CRC-HE-100K.zip -d data/raw/"
echo ""
echo "Option 3: Command Line (using curl)"
echo "  curl -L -o data/raw/NCT-CRC-HE-100K.zip 'https://zenodo.org/records/1214456/files/NCT-CRC-HE-100K.zip?download=1'"
echo "  unzip data/raw/NCT-CRC-HE-100K.zip -d data/raw/"
echo ""
echo "========================================"
echo "Dataset Classes (we use NORM and TUM):"
echo "========================================"
echo "  - NORM: Normal colon mucosa (~8,000 images)"
echo "  - TUM:  Colorectal adenocarcinoma (~14,000 images)"
echo "  - ADI:  Adipose tissue"
echo "  - BACK: Background"
echo "  - DEB:  Debris"
echo "  - LYM:  Lymphocytes"
echo "  - MUC:  Mucus"
echo "  - MUS:  Smooth muscle"
echo "  - STR:  Cancer-associated stroma"
echo ""
echo "For this binary classification project, we only use:"
echo "  Class 0 (Normal): NORM"
echo "  Class 1 (Cancer): TUM"
echo ""
echo "========================================"
echo "Citation:"
echo "========================================"
echo "Kather JN, et al. (2019). 100,000 histological images"
echo "of human colorectal cancer and healthy tissue."
echo "Zenodo. https://doi.org/10.5281/zenodo.1214456"
echo ""
